apiVersion: v1
kind: ConfigMap
metadata:
  name: job-service-config
  namespace: llm-mcp
data:
  SPRING_PROFILES_ACTIVE: k8s,gke
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: credit-service-config
  namespace: llm-mcp
data:
  SPRING_PROFILES_ACTIVE: k8s,gke
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: llm-worker-config
  namespace: llm-mcp
data:
  SPRING_PROFILES_ACTIVE: k8s,gke
